services:
  web-api:
    build: ./app/
    command: sh -c "sleep 10s" ; python3 ./Universidad.py"
    ports:
      - '7000:4000'
    depends_on:
      - mysql
  
  mysql:
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'universidad'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'